name: Flutter Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find pubspec.yaml
        id: find_pubspec
        run: |
          PUB=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)
          if [ -z "$PUB" ]; then
            echo "::error::ملف pubspec.yaml غير موجود في الريبو! يرجى رفعه أولاً."
            exit 1
          fi
          DIR=$(dirname "$PUB")
          echo "dir=$DIR" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: ${{ steps.find_pubspec.outputs.dir }}
        run: flutter pub get

      - name: Build APK
        working-directory: ${{ steps.find_pubspec.outputs.dir }}
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ steps.find_pubspec.outputs.dir }}/build/app/outputs/flutter-apk/app-release.apk
